import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'
import './AboutPage.css'

const CARDS= [
  {
    color:'#7E6377',
    icon:'📖',
    title:'A Universe of Books',
    body:'Between the Pages is a home for readers who want more than a list. Every book here is a world; with its own atmosphere, soundtrack, and story behind the story.',
  },
  {
    color:'#42303D',
    icon:'📃',
    title:'AI-Powered Summaries',
    body:'Each book gets a deep, thoughtful summary generated by Google Gemini; spoiler-aware, literary in tone, and refined by our team so it actually captures the essence of the work.',
  },
  {
    color:'#363B2E',
    icon:'🎶',
    title:'Soundtrack Your Read',
    body:'Every book has a mood. We pair each one with a curated Spotify playlist that matches its tone, era, and emotional world. Readers can add their own playlists too.',
  },
  {
    color:'#779273',
    icon:'🖼️',
    title:'Visual Moodboards',
    body:'Pinterest boards that capture the aesthetic of each story; the fashion, the architecture, the landscapes. See the world of the book before you open the first page.',
  },
  {
    color:'#5C3D4A',
    icon:'🎞️',
    title:'Cinematic Experiences',
    body:'For the most iconic books in literature, we build 30-second immersive entries; parallax scrolling, ambient sound, and a visual world that puts you inside the story before you begin.',
  },
  {
    color:'#2E3D2A',
    icon:'⭐',
    title:'A Community of Readers',
    body:'Leave reviews with a spoiler-toggle, suggest books we haven\'t added yet, share your own playlists and Pinterest boards, and connect with readers who love the same stories.',
  },
]

const fadeUp= (i=0)=> ({
  initial:{opacity:0,y:28},
  whileInView:{opacity:1,y:0},
  viewport:{once:true,margin:'-60px'},
  transition:{delay:i*0.08, duration:0.6, ease:[0.4, 0, 0.2, 1]},
})

export default function AboutPage() {
  return (
    <div className="about">
      <Navbar />
      <section className="about__hero">
        <div className="about__hero-inner">
          <motion.p className="eyebrow" {...fadeUp(0)}>The Inspiration</motion.p>
          <motion.h1 className="about__heading" {...fadeUp(1)}>
            Between the Pages<br />
            <em>is for readers who feel.</em>
          </motion.h1>
          <motion.p className="about__sub" {...fadeUp(2)}>
            Built because book apps felt cold. A list of titles and star
            ratings doesn't capture what it means to live inside a story for a
            week. So here something that hopefully comes close.
          </motion.p>
          <motion.div className="about__hero-actions" {...fadeUp(3)}>
            <Link to="/books" className="btn btn--sage">Browse Books</Link>
            <Link to="/register" className="btn btn--outline">Join the Community</Link>
          </motion.div>
        </div>
        <motion.blockquote
          className="about__hero-quote"
          initial={{opacity:0}}
          animate={{opacity:1}}
          transition={{delay:0.8,duration:1}}
        >
          <span className="about__hero-quote-mark" aria-hidden="true">"</span>
          A reader lives a thousand lives before he dies.
          <footer>by George R.R. Martin</footer>
        </motion.blockquote>
      </section>

      <section className="about__cards-section">
        <div className="about__cards-inner">
          <motion.p className="eyebrow about__cards-eyebrow" {...fadeUp(0)}>
            Features
          </motion.p>
          <div className="about__cards-grid">
            {CARDS.map((card, i)=> (
              <motion.div
                key={card.title}
                className="about-card"
                style={{'--card-color': card.color}}
                {...fadeUp(i*0.5)}>
                <span className="about-card__icon" aria-hidden="true">
                  {card.icon}
                </span>
                <h3 className="about-card__title">{card.title}</h3>
                <p className="about-card__body">{card.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
      <section className="about__values">
        <div className="about__values-inner">
          {[
            {num:'2,400+',label:'Books'},
            {num:'20+',label:'Experiences'},
            {num:'100%',label:'Ad-free'},
          ].map((v,i)=> (
            <motion.div key={v.label} className="about__stat" {...fadeUp(i*0.15)}>
              <span className="about__stat-num">{v.num}</span>
              <span className="about__stat-label">{v.label}</span>
            </motion.div>
          ))}
        </div>
      </section>
      <section className="about__close">
        <motion.div className="about__close-inner" {...fadeUp(0)}>
          <h2 className="about__close-title">
            Ready to step inside?
          </h2>
          <p className="about__close-sub">
            Find your next book, experience it fully, and leave your mark.
          </p>
          <Link to="/register" className="btn btn--sage about__close-btn">
            Create a Free Account
          </Link>
        </motion.div>
      </section>
    </div>
  )
}